server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: Qwzxqwzx1
    url: jdbc:postgresql://localhost:5432/online_store
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql